applications:
  # Bootstrap Project
  - name: bootstrap
    enabled: true
    source: https://redhat-cop.github.io/helm-charts
    chart_name: bootstrap-project
    source_ref: "1.0.1"
    values:
      serviceaccounts: ""
      # student is the GROUP NAME in IDM
      bindings: &binds
        - name: student
          kind: Group
          role: admin
        - name: jenkins
          kind: ServiceAccount
          role: admin
          namespace: neverbird-ci-cd
      namespaces:
        - name: neverbird-ci-cd
          bindings: *binds
          operatorgroup: true
        - name: neverbird-dev
          bindings: *binds
          operatorgroup: true
        - name: neverbird-test
          bindings: *binds
          operatorgroup: true
        - name: neverbird-stage
          bindings: *binds
          operatorgroup: true
  # Jenkins
  - name: jenkins
    enabled: true
    source: https://github.com/redhat-cop/helm-charts.git
    source_path: charts/jenkins
    source_ref: "jenkins-1.0.6"
    values:
      buildconfigs:
        # Jenkins S2I from Red Hat Labs
        - name: jenkins
          strategy_type: "Source"
          source_repo: https://github.com/rht-labs/s2i-config-jenkins.git
          source_repo_ref: master
          source_context_dir: '/'
          builder_image_kind: "DockerImage"
          builder_image_name: quay.io/openshift/origin-jenkins
          builder_image_tag: "latest"
        # Jenkins agents for running builds etc
        # default names, versions, repo and paths set on the template
        - name: jenkins-agent-npm
        - name: jenkins-agent-mvn
        - name: jenkins-agent-helm
        - name: jenkins-agent-argocd
      deployment:
        env_vars:
          - name: GITLAB_DEFAULT_BRANCH
            value: 'main'
          - name: GITLAB_HOST
            value: ''
          - name: GITLAB_GROUP_NAME
            value: ''
          - name: GIT_SSL_NO_VERIFY
            value: "true"
          - name: JAVA_ARGS
            value: '-Dorg.jenkinsci.plugins.gitclient.GitClient.untrustedSSL=true'
          - name: BISCUITS
            value: jaffa-cakes
      persistence: false
      source_secrets:
        - name: nexus-password
          username: admin
          password: admin123
# Nexus
  - name: nexus
    enabled: true
    source: https://redhat-cop.github.io/helm-charts
    chart_name: sonatype-nexus
    source_ref: "1.1.10"
    values:
      includeRHRepositories: false
      service:
        name: nexus
# Sealed Secrets
  - name: sealed-secrets
    enabled: true
    source: https://redhat-cop.github.io/helm-charts
    chart_name: helper-sealed-secrets
    source_ref: 1.0.3
    values:
      secrets:
        - name: git-auth
          type: kubernetes.io/basic-auth
          annotations:
            tekton.dev/git-0: https://github.com
            sealedsecrets.bitnami.com/managed: "true"
          labels:
            credential.sync.jenkins.openshift.io: "true"
          data:
            username: AgBm+jbl92VmLnoPQ6wTcxyNKYJSsClpZS1jcXlSJiSIZASe8BXhyY4hqweMc+4GFZ50yBMIIvDQn+qxacWgGuZ5k3HRKyCoYf4zKJylDHdM9IzkAxqy9LflbzrWK4b2L+aGjrP0ViK6GwRfMhYBkguegLVxFecx0UUqkJAvQFqnGtDeT417Q2fvmXxepRmI/wqq/xcFT9TrXvRmGwaaGP2GwGL8IutgPozk3XPTc5CpcBtA9Zrez3sHPdlnunv9PeUYBfrwSE5VDqbMmw5CATME4UfZTOTpNATBYVli4h2DguJ2mpkAcWoXgcHFlu5W7nfqu1cUnnIxXAitlkRA6c8WyeXTlKwDjq5RsQfUghNzPivbJUECSWrlN8HgR2GoG4qPc7EioFhayKb9sTRM+PsCkNKdaUzkNWInSkvp5+ilwkvALtekXty7PJ5Gyr/Zvpg8u0M8ewZ/PAUeMhEIA5mtqiR2K4qdL9jvgEZkjPhnpHh6yAYiZ8Ak4U5J+7vNL9EKtWBMqTs8LBkNSa8mWjKmKVo2igATagUWczVWS3aply5J5F+mR71xmWLuT3mvBhu2IwcY/rR7ht5EdZQaH4r0y7XTndNgEhxkbHgqdDG5V2VMXMMZ3rs9F+P8eJPH/dXhjSVbwFO3QXe8mLXJWLx2Z2IKZ/r+zDktkrOE27l1wLr5hEjvGnqpdfKm6I9DKOY=
            password: AgB5hI1bwvewf6hjimh4/741qcYwkfwZ7w79HIKSOOcY25fphqfLX2uotSovI0uZDFIp/fGIECDf/ZZY+clL1fiyin0VT6799nNPlEtyyeBd4pDc9JNaWfnw768umcIyDTBf2pXD//MCt4S3R9mDieNEVglAJ/WnuaHBDSq48ARwGXliZsd+9X+36n6F6KxeR6U5aSOy9d6XV0/NORjrqa4lSOL7qaShbn+rBSb6RRR6tOvTcp0+RbMxvwu3yK9IbFHjUKDMJudjcaSgpTlCVCksd29x8snrdkRCl4Hb2DX6pLXyLWYrFrDnaEe1MhXwUCMnmeSi5NCoS5Y6vBb/ydraPj8hK0YyP7cxJH9AodCVStRYqd2RK7oPRNcy0GhoCZnyjFq/r7MD7MXKFqfADAPElFzKg6+Hn1/CGeV+Fr4RWpJOJRltgotm+pmP4+BJlFbPmXyBd4KausMABfE5DReyorDGGBiL3zh5yHRd9yBJ9yIK7UO+DjIRRpO1p6qSwH99cET6UFBbGVykOhhbq2P7sxg2GO3/MXjHhVre4Xvj9BhWIEDk1yz4ZGRStSRG+O2E/rDAKVzjQG2Kn0ZE5qT8Z1CEHZk1urnkn3EX25Bxrko5EN74zXd6kba+ATLdTgfM0HhfH5MEGAWSi8sj5RgObpzU68n8f+BGkUZrUKVUQFg9IYjI+8/lU4VefBCTmHxYnsIZvjE30kpIURdpWkM+yCPj9SO7+fE8CW9qv/khutHhd1dZJsBi
# Grafana

# Allure

# Matomo
