applications:
  # Bootstrap Project
  - name: bootstrap
    enabled: true
    source: https://redhat-cop.github.io/helm-charts
    chart_name: bootstrap-project
    source_ref: "1.0.1"
    values:
      serviceaccounts: ""
      # student is the GROUP NAME in IDM
      bindings: &binds
        - name: student
          kind: Group
          role: admin
        - name: jenkins
          kind: ServiceAccount
          role: admin
          namespace: neverbird-ci-cd
      namespaces:
        - name: neverbird-ci-cd
          bindings: *binds
          operatorgroup: true
        - name: neverbird-dev
          bindings: *binds
          operatorgroup: true
        - name: neverbird-test
          bindings: *binds
          operatorgroup: true
        - name: neverbird-stage
          bindings: *binds
          operatorgroup: true
  # Jenkins
  - name: jenkins
    enabled: true
    source: https://github.com/redhat-cop/helm-charts.git
    source_path: charts/jenkins
    source_ref: "jenkins-1.0.6"
    values:
      buildconfigs:
        # Jenkins S2I from Red Hat Labs
        - name: jenkins
          strategy_type: "Source"
          source_repo: https://github.com/rht-labs/s2i-config-jenkins.git
          source_repo_ref: master
          source_context_dir: '/'
          builder_image_kind: "DockerImage"
          builder_image_name: quay.io/openshift/origin-jenkins
          builder_image_tag: "latest"
        # Jenkins agents for running builds etc
        # default names, versions, repo and paths set on the template
        - name: jenkins-agent-npm
        - name: jenkins-agent-mvn
        - name: jenkins-agent-helm
        - name: jenkins-agent-argocd
      deployment:
        env_vars:
          - name: GITLAB_DEFAULT_BRANCH
            value: 'main'
          - name: GITLAB_HOST
            value: ''
          - name: GITLAB_GROUP_NAME
            value: ''
          - name: GIT_SSL_NO_VERIFY
            value: "true"
          - name: JAVA_ARGS
            value: '-Dorg.jenkinsci.plugins.gitclient.GitClient.untrustedSSL=true'
          - name: BISCUITS
            value: jaffa-cakes
      persistence: false
      source_secrets:
        - name: nexus-password
          username: admin
          password: admin123
 # Nexus
  - name: nexus
    enabled: true
    source: https://redhat-cop.github.io/helm-charts
    chart_name: sonatype-nexus
    source_ref: "1.1.10"
    values:
      includeRHRepositories: false
      service:
        name: nexus
# Sealed Secrets
  - name: sealed-secrets
    enabled: true
    source: https://redhat-cop.github.io/helm-charts
    chart_name: helper-sealed-secrets
    source_ref: 1.0.3
    values:
      secrets:
        - name: git-auth
          type: kubernetes.io/basic-auth
          annotations:
            tekton.dev/git-0: https://github.com
            sealedsecrets.bitnami.com/managed: "true"
          labels:
            credential.sync.jenkins.openshift.io: "true"
          data:
            username: AgB788KkIRoeyCcpUSR3ZjfOBZSDWiszK1kgz84bckl/gf//POPJCWaYtDcGtP+vYIvwtT4a+cwJaKY0Hg6N0sw3q56LH09qXlz5GNt/NjEoysdaVD/E5+TRd8ligipDPnTo6zffxAn2HzjyGwI+ZhkWrXarN04M1Nr+pfmJV1E4dm6y1KMedZSSODON9J880rsebvpTgT4bVgD4qY+kIfs1MNaqwNz9Ev8v02pv13ICzOhXsa5jZHkg/XzshnEmRC4IcU2oM9OHG1x0sVxguwEmI1gG9T1MQiarvQZIMMdw3XYIjfiBAbXkkiWFn6GtQYylc5jRaH6KC0H7cdgZdeCbilBQqXGm2w79cMKslNvU4vP41Nljo3m2zk8b9QXDBSDjq88GlI628TZnAPpOapAt3+SuMTTVW7G8M0Yx+fqBQGCbFlIi81Zm8oPiIT4vNrZytTAborHYdsveYndazHJQP619R/e9SI16sKAsWdrs0r9iUjEyF/KyRxhqTYrwWEl3zxmttxzYHZ3a0mzDla1wAjU+Vjevrsy/eRdZETBp+IFcpvHMRqo7uSa+VfjrlJT4ANOhmuWTiYEyfYcqey/WAFBm9NVq6Ss5QKSZL5mKTFtRzgLfyGWO6qFhtggTeOFN1P3mDkzAJSKc/ZOOlqIPsiO38XWtHpYg3x024zrX3E1x2RgGMD3p6KbwhmLvkBp15geeIJ3IGMI=
            password: AgBZlRprDyuMjbURW4sJqzKjXvZM0JEFDbaYmO3/LStremhk113rdlnhDVvSjMS90FQ2EWu9O634l0ytPmPy3LcWlEhJSSRNK4JwyPFZd+9OCZlltMkpXYAvTT4PHV/SYUPxJmGph7+S15yyuI/Iuy/vOoMgLC5/qrEMYYX6jDI4BxGzmbQfELGtduOkoSl5r0FyRz84J4Kti7BB2aHT0JAvAssK+CviZc9LVqj1dfHSAMlvRHUjEvgBsk//nGAix8EsYPlm0AHjixS33YcMHHEpLSMwGwmHchgH7wAgoUP0QO+9LiTsr/++kYxWo+NtQ2szeQCfA6UMl/hkifkp4L9qNMWzz2Kn4Y3wMShthOpHuZYo8XSASokG7hwW4re9Qe6kxmXQ64xLp1Q4Dz1ag96vwMuIRwpqDy1nl8WIvoQp9LnF3Ha6H0P8shZiL29kuYYdrW6ZAq637jEcowYHkD0DuMOKMm5YrJVnOG+ROFMpBAsacpwBCr6pGBoKttlVfKVaztAHvPlUTp+dThA0H3LECCgGGG3B/9RPEi9CN2TSzXjAC9wBPiV1oyLyEYElPgfHZ61NokwDYTke8lZGmEYQPzZlo73Nsv6HuHN/U2Qzt10zg/XegFX94BqprqiFyAb+PXGL7qP6K/GQtbuQnSKEc/ffcNAhOKClKJ35fFfe8oz7pfCIEC8ReIBPQPZ69a3WY7yn4eTBPpvQXQoabfioF24EwW/F181gAke5ICTfCPRg4Ig2To0B
# Tekton Pipelines

# Sonarqube

# Grafana

# Allure

# Matomo
